Disable: android.hardware.vibrator-V2-ndk
Since Build Environment cannot find The NDK vAriant AIDL Service i'm Gonna Have To Disable It For Successfull compilation

Error: device/samsung/exynos850-common/aidl/vibrator/Android.bp:7:1: dependency "android.hardware.vibrator-V2-ndk" of "android.hardware.vibrator-service.exynos850" missing variant:
  os:android,image:vendor.32,arch:arm64_armv8-a_cortex-a53,sdk:,link:shared
available variants:
  os:android,image:,arch:arm64_armv8-a_cortex-a53 (alias to os:android,image:,arch:arm64_armv8-a_cortex-a53,sdk:,link:shared,version:)